name: deploy
on:
  push:
    tags:
      - v*
    branches:
      - master
      - develop
      - newapp
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  docker-deploy:
    steps:
      - uses: actions/checkout@v3
      - run: sh build.sh
